site_name: TheH4ckademy
site_url: https://theh4ckademy.github.io/

theme:
  name: shadcn
  language: en

nav:
  - 🧠 TheH4ckademy: index.md
  - TryHackMe: 
    - Ledger: TryHackMe/ledger.md
    - Reset: TryHackMe/reset.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets

